### ISSUE TITLE
Title screen logo.dds has large compression artifacts

### ISSUE THREAD

**Issue by Sonamaker1** [HTV04/funkin-rewritten#1]
I've made a new one using crunch (crnlib):  [logo.dds](https://github.com/Sonamaker1/funkin-rewritten/blob/main/src/love/images/dds/menu/logo.dds)

This was only necessary for the title screen logo, as no other dds graphics generated with texconv appear to have noticeable compression artifacts. When running the conversion script, I just paste this one in for the title screen.

**Comment by HTV04** [comment]
I appreciate it, but I'd rather stick to the current logo.dds generated by the script for simplicity's sake. I think the issue is that the logo uses a weird sRGB format or something, so it might be fixable without using a replacement image.
