### ISSUE TITLE
Another bug when building switch version 

### ISSUE THREAD

**Issue by pokeyjojo** [HTV04/funkin-rewritten#10]
Hi (sorry for all the issues im new to this stuff) but when building i get this error `make: elf2nro: No such file or directory
make: *** [Makefile:30: switch] Error 127
` did i set up the dependencies wrong?

**Comment by HTV04** [comment]
You need to install devkitPro. Refer to this guide: https://devkitpro.org/wiki/Getting_Started

**Comment by pokeyjojo** [comment]
weird i did i used the graphical installer and was running via the devkitpro mysys shell

**Comment by HTV04** [comment]
Try running this: export PATH=${DEVKITPRO}/tools/bin:$PATH

Then running the Makefile again. This might be something with the Windows version of devkitPro I need to look into.

**Comment by pokeyjojo** [comment]
Great! that worked thanks for helping with all of the issues i have (i'll probably have more in the future)

**Comment by HTV04** [comment]
No problem!
