### ISSUE TITLE
Songs not playing in switch branch 

### ISSUE THREAD

**Issue by pokeyjojo** [HTV04/funkin-rewritten#11]
Yup im back with another  issue when my songs load the chart loads the background loads (but in the incorrect size) but the music doesnt play just the miss sounds  what is the problem here?

**Comment by HTV04** [comment]
You might be using an outdated version of LOVE Potion that has the infamous audio bug. Download the latest build here: https://github.com/lovebrew/LovePotion/suites/3441735497/artifacts/81610107

**Comment by pokeyjojo** [comment]
yea it seem to fix itself after restarting my switch hopefully this provides a more stable way of preventing this bug
