### ISSUE TITLE
weeks/week5.lua:270 attempt to call field ‘cancelTimer’ (a nil value)

### ISSUE THREAD

**Issue by Temmie72832l** [HTV04/funkin-rewritten#19]
Platform: Nintendo Switch

weeks/week5.lua:270: in function <weeks/week5.lua:198
(tail call): ?
main.lua:145: in function ‘update’
[C]: in function ‘xpcall’
.
simpler explanation on what I think is happening: Week 5s transition to Winter horrorland is broken.

**Comment by HTV04** [comment]
What version of FNFR did this error occur on?

**Comment by Temmie72832l** [comment]
1.1.0-switch beta 1

**Comment by HTV04** [comment]
Please update to v1.1.0 beta 2.
