### ISSUE TITLE
Assets not loading

### ISSUE THREAD

**Issue by tedmakesstuff** [HTV04/funkin-rewritten#22]
I tried the lovefile out on LOVE 11.3 on a Raspberry Pi 400 but most assets seem to not load.
Week 4 BG loads, all pixela assets load, skid and pump load, week 4 bf and gf load, Christmas bg loads, Christmas bf loads
some other things that I missed probably load as well
everything else doesn't load

**Comment by GalaxytedYT** [comment]
i forgot to mention, week 1 loads as well (bg and dd)

**Comment by GuglioIsStupid** [comment]
If you're talking about them becoming squares then I get this exact same issue.
I've always assumed it was the amount of graphics memory on the Pi4 but idk anymore.

**Comment by GalaxytedYT** [comment]
the same issue, it's actually also on android, when I posted this I didn't read that issue.

**Comment by Fordi** [comment]
Just ran into this from a fresh build of löve 11.3 - though it appears not to happen on a similar fresh build of löve main on Ubuntu on an x86.  The `./configure` output is marginally different... (attached; it's mostly different ways to get luajit - I don't think it's the cause).

I'll dig in a little harder, maybe running funkin' from sources.

[love-configure-raspbian.txt](https://github.com/HTV04/funkin-rewritten/files/8829009/love-configure-raspbian.txt)
[love-configure-ubuntu.txt](https://github.com/HTV04/funkin-rewritten/files/8829011/love-configure-ubuntu.txt)
.

**Comment by Fordi** [comment]
For anyone looking, the issue @tedmakesstuff is referring to is #14

**Comment by theofficialgman** [comment]
> I tried the lovefile out on LOVE 11.3 on a Raspberry Pi 400 but most assets seem to not load. Week 4 BG loads, all pixela assets load, skid and pump load, week 4 bf and gf load, Christmas bg loads, Christmas bf loads some other things that I missed probably load as well everything else doesn't load

week 4 bf and gf are image size 4096x4096. the pi4 gpu can only handle textures up to 4096x4096. everything else will fail to load. for this game, that currently means all of these textures will failed to reload as they are larger than 4096 in at least on dimension

```
boyfriend.png
girlfriend.png
menu/girlfriend-title.png
week2/haunted-house.png
week4/mommy-mearest.png
week5/dearest-duo.png
week5/girlfriend.png
week5/monster.png
```

devs are aware of this limitation in the discord of the pi gpu and may make code changes to work around it.
