### ISSUE TITLE
attempt to index a nil value

### ISSUE THREAD

**Issue by Piratefoxy216** [HTV04/funkin-rewritten#24]
I was playing around with the source code, I only added a custom song though, no editing of anything else, I was play a song then randomly a error occurred

modules/graphics.lua:155: attempt to index a nil value

Traceback

[love "callbacks.lua"]:228: in function 'handler'
modules/graphics.lua:155: in function 'animate'
states/weeks.lua:565: in function 'safeAnimate'
states/weeks.lua:692: in function 'updateUI'
weeks/week7.lua:116: in function 'update'
main.lua:131: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by Piratefoxy216** [comment]
Nevermind, its because of the part when tankman talks so.. Sorry

**Comment by AM7999** [comment]
week7 porter spotted

**Comment by GuglioIsStupid** [comment]
bruh
![image](https://user-images.githubusercontent.com/96344386/166849814-57c52b09-3863-469d-9154-1b4721a026ec.png)

**Comment by AM7999** [comment]
you know i just had to do it

**Comment by Piratefoxy216** [comment]
> week7 porter spotted

I am just doing this for fun, this is not going to be published anywhere

**Comment by AM7999** [comment]
don't mind lmao I said that as a joke (totally didn't steal what @GuglioIsStupid said)
