### ISSUE TITLE
Raspberry Pi: Squares instead of sprites

### ISSUE THREAD

**Issue by m3957** [HTV04/funkin-rewritten#26]
![Friday Night Rewritten Sprites are squares](https://user-images.githubusercontent.com/86982093/172486943-db1d973c-38c4-4506-ae28-02a201aadb54.png)
On certain weeks, sprites are squares.

Raspberry Pi OS Lite - Xfce - Installed the game from Pi-Apps

**Comment by AM7999** [comment]
Please look at one of the pinned issues.

**Comment by GuglioIsStupid** [comment]
See #14

**Comment by m3957** [comment]
Ok! Great game!
