### ISSUE TITLE
[Switch] Error sprites/menu/girlfriend-title.lua:21:

### ISSUE THREAD

**Issue by Brelook** [HTV04/funkin-rewritten#29]
Error 
sprites/menu/girlfriend-title.lua:21: Cannot create image (OpenGL error: out of memory)

Traceback

[C]: in function 'nameimage'
sprites/menu/girlfriend-title.lua:21: in main chunk
[C]: in function 'require'
main.lua:42: in function 'load'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by claus296** [comment]
Use the mass dds converter

**Comment by GuglioIsStupid** [comment]
> Use the mass dds converter

To add more context: This error occurs when the current system runs out of memory to load all the images, DDS files help prevent this type of error by using way less memory as standard png's use

run the mass converter script to automatically convert all images to dds

**Comment by GuglioIsStupid** [comment]
You must be using a pc for the converters to work

**Comment by AncientEntity** [comment]
Is there a guide I can follow to DDS Convert?

**Comment by GuglioIsStupid** [comment]
All you need to do is run the batch/sh file

**Comment by AncientEntity** [comment]
Oh thanks, I just followed what the releases said and put the .nro in the switch/ directory
