### ISSUE TITLE
MacOS Version says the file is corrupted.

### ISSUE THREAD

**Issue by Ali-Nothing-Creative** [HTV04/funkin-rewritten#3]
I'm on MacOS and whenever I download the Mac .zip file, i open it and it gives me an error that says as follows:

_"Friday Night Funkin' Rewritten.app" is damaged and can't be opened. You should move it to the Trash._
WIth two buttons: "Cancel" and "Move to Trash"

![image](https://user-images.githubusercontent.com/66648090/126875723-6efa3461-7cd8-4770-85a1-efcecf22ac95.png)

I've tried redownloading the zip multiple times, through both the GitHub and GameBanana links, but it still won't work.

Any help is much appreciated!

**Comment by HTV04** [comment]
Hmm, it works fine for me. What version of macOS are you using? And what did you use to extract the ZIP? File permissions are important for macOS apps.

**Comment by HTV04** [comment]
Were you able to get it to work?

**Comment by Ali-Nothing-Creative** [comment]
Sorry I couldn't respond sooner, but no, its still dosen't work.
I'm using MacOS 10.13.6 (High Sierra) & I used the deafult MacOS unzipping tool.

**Comment by HTV04** [comment]
> I'm using macOS 10.13.6 (High Sierra)
That might be the issue. FNF Rewritten has only been tested on macOS Big Sur (11.0), and I believe LOVE only supports a few macOS versions before it.

**Comment by Ali-Nothing-Creative** [comment]
> > I'm using macOS 10.13.6 (High Sierra)
> 
> That might be the issue. FNF Rewritten has only been tested on macOS Big Sur (11.0), and I believe LOVE only supports a few macOS versions before it.
> 
> Are you able to update your system to a newer macOS version?

No, sadly not.

**Comment by HTV04** [comment]
Unfortunately FNF Rewritten won't be able to support any platforms or operating systems LÖVE can't support, sorry.

You might be able to run it by installing another operating system, like Linux (which I would recommend for your device) or Windows 10.

**Comment by Ali-Nothing-Creative** [comment]
Ah, ok. Thanks.

**Comment by HTV04** [comment]
Turns out this may have been another issue entirely, due to something with signatures.

I uploaded a fixed binary to the v1.0.1 release, can you check if this works?

https://github.com/HTV04/funkin-rewritten/releases/download/v1.0.1/funkin-rewritten-macos.zip

**Comment by HTV04** [comment]
@Ali-Nothing-Creative This issue has been inactive for a while, and macOS users have been reporting that the new build works so I'll have to close it

Let me know if the new macOS build works for you, though
