### ISSUE TITLE
visual problem

### ISSUE THREAD

**Issue by Otamamori917** [HTV04/funkin-rewritten#33]
on **raspberry pi** there is a flashing pink and white part that covers part of the menu and the entire background of the game _(keys and bar are still visible)_
**game works perfectly**
![Screenshot from 2023-04-03 01-37-51](https://user-images.githubusercontent.com/117782096/229389310-1eddcc12-19bc-405c-9584-44c5f7365254.png)
![Screenshot from 2023-04-03 01-46-57](https://user-images.githubusercontent.com/117782096/229389312-77c2f342-4030-4d4d-92b5-0a10d48afe2d.png)

**Comment by AM7999** [comment]
See pinned issue

**Comment by AM7999** [comment]
or See: https://github.com/HTV04/funkin-rewritten/issues/14

**Comment by Otamamori917** [comment]
Oh OK it's already know kk
