### ISSUE TITLE
The way Score is printed in Week 5 is coded separately from the rest of them.

### ISSUE THREAD

**Issue by ZGURemixer** [HTV04/funkin-rewritten#4]
While making my own fork of this amazing rewrite I have noticed how the way the score in week 5 is coded separately from the way it is coded in the other weeks. I have tried to recreate FPS Plus'/Kade Engine's display using this project as a base when I ran into this issue. Is there a way that the color switch can be implemented differently so the way the score looks can be easier to modify?

**Comment by HTV04** [comment]
It'd take some extra code to implement this (perhaps a flag passed to the function), but for now, it's worth nothing that the code for drawing the score text in Week 5 is identical to that of weeks.lua, just with some extra code to make the score text black.
