### ISSUE TITLE
Adding new .jsons/editing notes(Don't know where to post this, new to GitHub)

### ISSUE THREAD

**Issue by SonGokuSSJGOD** [HTV04/funkin-rewritten#7]
Does anyone know how to edit and or add notes/json on the source code for a mod. I got everything working (music, skins, bg, etc.) but the only problem I'm having is I don't know how to edit or put a new json in there.

**Comment by HTV04** [comment]
Have you tried using the funkin-json script in the tools folder? Just drag the JSON file you want to convert there, and add the generated Lua file to the charts folder in the game's source code.

**Comment by SonGokuSSJGOD** [comment]
I've tried and I can't open it is there a program to use it with a program? I tried using Python and it says that It's not the right version for my pc or I just can't open the file itself.

**Comment by HTV04** [comment]
What OS do you use?

**Comment by SonGokuSSJGOD** [comment]
Windows 10 64 bits. I tried this on my Virtual Machine Windows 11 64 bits and same thing.

**Comment by SonGokuSSJGOD** [comment]
Windows 11 64 bits.

**Comment by HTV04** [comment]
Try downloading this version of Python: https://www.python.org/ftp/python/3.9.6/python-3.9.6-amd64.exe

**Comment by SonGokuSSJGOD** [comment]
I'm not sure what I'm doing wrong. I can't drag and drop the file and I can't open Individually. Do we drag the file or open individually. If I have to drag and drop it then I'm not sure how cause it won't let me drop the .json file into the .py file.

**Comment by HTV04** [comment]
You can try running it via the cmd: funkin-json.py (insert name of json file)

The cmd must currently be set to the directory the Python script is in

**Comment by HTV04** [comment]
Closing this issue because it's invalid, but if you hop on the Discord server I can try to help you with this further: https://discord.gg/tQGzN2Wu48
