### ISSUE TITLE
 Switch Building error? (probably me setting up dependencies wrong)

### ISSUE THREAD

**Issue by pokeyjojo** [HTV04/funkin-rewritten#9]
when building switch version i get this error
`/bin/sh: line 1: zip: command not found
make: *** [Makefile:24: lovefile-switch] Error 127
` how do i fix this?

**Comment by HTV04** [comment]
You need to install the "zip" package using your package manager.

**Comment by pokeyjojo** [comment]
oh im using windows but Thanks!
